---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-pack-configs
  annotations:
    description: StackStorm pack configs defined in helm values, shipped in (or copied to) '/opt/stackstorm/configs/'
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.packs.configs | indent 2 }}
