{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-st2web-ingress
  labels:
    app: ingress
    tier: frontend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
      {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
        - path: {{ default "/*" .path }}
          backend:
            serviceName: {{ .serviceName }}
            servicePort: {{ .servicePort }}
      {{- end }}
  {{- else }}
    {{- if required "Missing context '.Values.st2web.service.hostname'!" .Values.st2web.service.hostname }}
  - host: {{ .Values.st2web.service.hostname }}
    {{- end }}
    http:
      paths:
        - path: "/"
          backend:
            serviceName: {{ .Release.Name }}-st2web
            servicePort: 80
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end }}
