---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-kv
  annotations:
    description: Key/Value pairs to save in StackStorm's datastore
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  st2kv.yaml: {{ tpl (toYaml .Values.st2.keyvalue ) . | b64enc | quote }}
