{{- if .Values.rabbitmq.enabled }}
# This configuration is a workaround to https://github.com/bitnami/charts/issues/4635
# This code block should be dropped once the above issue is resolved and definitions can be defined as shown in
# https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-definitions
  annotations:
    description: A rabbitmq definition which will be loaded by the rabbitmq subchart to enable mirroring for Rabbit HA
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rabbitmq-definitions.json:  {{ tpl (.Files.Get "conf/rabbit-definition.conf") . | b64enc }}
{{- end }}
