---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-apikeys
  annotations:
    description: A list of StackStorm API keys with metadata that will be imported into the system
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  apikeys.yaml: {{ toYaml .Values.st2.apikeys | b64enc | quote }}
