apiVersion: v2
appVersion: "3.6"
dependencies:
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 8.0.2
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 10.0.1
- condition: external-dns.enabled
  name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 4.0.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 12.3.2
description: StackStorm K8s Helm Chart, optimized for running StackStorm in HA environment.
home: https://stackstorm.com/
icon: https://landscape.cncf.io/logos/stack-storm.svg
keywords:
- st2
- stackstorm
- devops
- SRE
- automation
- chatops
- event-driven
- auto-remediation
- IFTTT
- HA
maintainers:
- email: armab@stackstorm.com
  name: Eugen Cusmaunsa
  url: https://github.com/armab
name: stackstorm-ha
version: 0.80.0
